CREATE DATABASE PASTELERIA;
USE PASTELERIA;


CREATE TABLE CLIENTE (
	ID_CLIENTE INT NOT NULL AUTO_INCREMENT COMMENT 'Primary Key de Cliente',
    NOMBRE VARCHAR(45) NOT NULL COMMENT 'Nombre del cliente',
    CONTRASENIA VARCHAR(45) NOT NULL COMMENT 'Contraseña del cliente', 
    FECHA_NAC DATE NOT NULL COMMENT  'Fecha de nacimiento del cliente', 
    PRODUCTO VARCHAR(45) NOT NULL COMMENT 'Producto del cliente', 
    EMAIL VARCHAR(45) NOT NULL COMMENT 'Correo electronico del cliente', 
    TELEFONO VARCHAR(45) NOT NULL COMMENT 'Telefono del cliente',
	PRECIO_PEDIDO DECIMAL(8,2) COMMENT 'Precio de la cesta del cliente', 
    OBSERVACIONES VARCHAR(45) COMMENT 'Observaciones sobre el cliente',
    ESTADO VARCHAR(45) NOT NULL COMMENT 'Estado del pedido del cliente',
    CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE)
);

CREATE TABLE PRODUCTO (
	ID_PRODUCTO INT NOT NULL AUTO_INCREMENT COMMENT 'Primary Key de Producto',
    NOMBRE VARCHAR(45) NOT NULL COMMENT 'Nombre del producto',
    DESCRIPCION VARCHAR(45) NOT NULL COMMENT 'Descripcion sobre el producto', 
    PRECIO DECIMAL(8,2) NOT NULL COMMENT 'Precio del producto',
    STROCK INT NOT NULL COMMENT 'Stock del producto',
    CATEGORIA VARCHAR(45) NOT NULL COMMENT 'Categoria del producto',
    CONSTRAINT PK_PRODUCTO PRIMARY KEY (ID_PRODUCTO)
);

CREATE TABLE PEDIDO (
	ID_PEDIDO INT NOT NULL AUTO_INCREMENT COMMENT 'Primary key de Pedido',
    PENDIENTE VARCHAR(45) NOT NULL COMMENT 'Estado del pedido en pendiente',
    ENTREGADO VARCHAR(45) NOT NULL COMMENT 'Estado del pedido en entregado',
    ID_PRODUCTO INT NOT NULL,
    ID_CLIENTE INT NOT NULL,
    CONSTRAINT PK_PEDIDO PRIMARY KEY (ID_PEDIDO),
    CONSTRAINT FK_PRODUCTO_PEDIDO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO),
    CONSTRAINT FK_CLIENTE_PEDIDO FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)
);

CREATE TABLE INGREDIENTE (
	ID_INGREDIENTE INT NOT NULL AUTO_INCREMENT COMMENT 'Primary Key de Ingrediente',
    NOMBRE VARCHAR(45) NOT NULL COMMENT 'Nombre del ingrediente',
    PRECIO DECIMAL(8,2) NOT NULL COMMENT 'Precio del ingrediente',
    STOCK INT NOT NULL COMMENT 'Stock sobre el ingrediente',
    FABRICANTE VARCHAR(45) NOT NULL COMMENT 'Fabricante del ingrediente', 
    CONSTRAINT PK_INGREDIENTE PRIMARY KEY (ID_INGREDIENTE)
);

CREATE TABLE INGREDIENTE_PRODUCTO (
	ID_INGREDIENTE INT NOT NULL,
    ID_PRODUCTO INT NOT NULL,
    CONSTRAINT FK_INGREDIENTE_INGREDIENTE FOREIGN KEY (ID_INGREDIENTE) REFERENCES INGREDIENTE (ID_INGREDIENTE),
    CONSTRAINT FK_PRODUCTO_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO)
);

CREATE TABLE EMPLEADO (
	ID_EMPLEADO INT NOT NULL AUTO_INCREMENT COMMENT 'Primary key de Empleado',
    NOMBRE VARCHAR(45) NOT NULL COMMENT 'Nombre del empleado',
    APELLIDO VARCHAR(45) NOT NULL COMMENT 'Apellido del empleado', 
    TELEFONO VARCHAR(45) NOT NULL COMMENT 'Telefono del empleado', 
    FECHA_CONTRATACION DATETIME NOT NULL COMMENT 'Fecha de contratacion del empleado', 
    FECHA_ENTRADA DATETIME NOT NULL COMMENT 'Fecha de entrada del empleado',
    FECHA_SALIDA DATETIME NOT NULL COMMENT 'Fecha de salida del empleado', 
    CONSTRAINT PK_EMPLEADO PRIMARY KEY (ID_EMPLEADO)
);
